### ISSUE TITLE
Stylings

### ISSUE THREAD

**Issue by sophie97yang** [sophie97yang/Parmazon-Prime#28]
- Make pages responsive to screen width: mainly for mobile devices
- Login Page:
  - Strict height of main div so that footer doesn't come up
- Landing Page
  - Making heights of carousel images the same (DONE)
- Sign Up Page
  - Input fields aligned and take up more width
- Your Orders Page
  - Return button shouldn't show up if you've made a return 
  - Return button should have white text
-   Create Review Page
    - Make it more similar to Amazon 
    - Instead of numerical value, have users choose stars 
    - "Add a Review for {product name}"
    - Move Remy to the center
- Tab Icon
   - Rounded Edges 
- Update Review Page
   - ADD PADDING
- Modals 
  -  "X" icon that will close modal
  - Cancel button that gives users options to cancel their changesz 
-  Product Details Page
   - Style reviews list 
   - Keep images with their reviews

**Comment by yoslatif** [comment]
- added padding to update review modal 
- added 5 star "cheese" selector instead of choosing score out of 5. (not pushed yet)
